name: Deploy to AWS

on:
  push:
    branches:
      - main # Se activa cuando haces push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajar tu código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Instalar dependencias y Construir
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4. Configurar las llaves de AWS (Las toma de los secretos que creaste)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Subir a S3 (¡CAMBIA EL NOMBRE DEL BUCKET AQUÍ ABAJO!)
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://academia-bluewater-karcabcas --delete

      # 6. Limpiar la caché de CloudFront para que se vea el cambio
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
